import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "The Burger Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image.png" />
      </head>
      <body className={`${inter.className} antialiased min-h-screen `}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
